# Generated by Django 5.2.8 on 2025-11-23 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auction", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="condition",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("used", "Used"),
                    ("refurbished", "Refurbished"),
                ],
                default="used",
                max_length=20,
            ),
        ),
    ]
